contact_links:
- name: Question/Help/Support
  url: https://github.com/jcreinhold/intensity-normalization/discussions
  about: "All general questions not covered by the documentation should go to 'Discussions'."
